# Generated by Django 5.0 on 2023-12-19 15:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_reviews_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AddConstraint(
            model_name='reviews',
            constraint=models.CheckConstraint(check=models.Q(('rating__gte', 1), ('rating__lt', 5)), name='A qty value is valid between 1 and 10'),
        ),
    ]
